# Generated by Django 4.2.25 on 2025-10-19 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['nombre'], 'verbose_name': 'Categoría', 'verbose_name_plural': 'Categorías'},
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='email_verificacion',
        ),
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='nombre',
            field=models.CharField(default=1.0, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='direccion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='email_verificado',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(blank=True, choices=[('cliente', 'Cliente'), ('administrador', 'Administrador'), ('cajero', 'Cajero'), ('repatidor', 'Repatidor'), ('cocina', 'Cocina')], max_length=20, null=True),
        ),
    ]
