# Generated by Django 4.2.25 on 2025-10-19 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_categoria_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(blank=True, choices=[('cliente', 'Cliente'), ('administrador', 'Administrador'), ('cajero', 'Cajero'), ('repartidor', 'Repartidor'), ('cocina', 'Cocina')], max_length=20, null=True),
        ),
    ]
