# Generated by Django 4.2.25 on 2025-10-20 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_carrito_metodopago_pedido_reclamo_detallepedido_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemcarrito',
            options={'verbose_name': 'Item del Carrito', 'verbose_name_plural': 'Items del Carrito'},
        ),
    ]
