# Generated by Django 4.2.25 on 2025-10-20 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_itemcarrito_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reclamo',
            old_name='atendido',
            new_name='atendido_por',
        ),
        migrations.RenameField(
            model_name='reclamo',
            old_name='despcripcion',
            new_name='descripcion',
        ),
        migrations.AlterField(
            model_name='reclamo',
            name='estado',
            field=models.CharField(choices=[('nuevo', 'Nuevo'), ('en_revision', 'En Revisión'), ('respondido', 'Respondido'), ('resuelto', 'Resuelto'), ('cerrado', 'Cerrado')], default='nuevo', max_length=20),
        ),
    ]
