# Generated by Django 4.2.25 on 2025-10-22 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_atendido_reclamo_atendido_por_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(help_text='Tamaño recomendado: 1200x600px', upload_to='slides/')),
                ('titulo', models.CharField(blank=True, help_text='Título principal que aparece sobre la imagen.', max_length=100, null=True)),
                ('subtitulo', models.CharField(blank=True, help_text='Texto secundario debajo del título.', max_length=200, null=True)),
                ('texto_boton', models.CharField(default='Ver más', max_length=50)),
                ('link_boton', models.CharField(help_text='Enlace del botón. Ej: /catalogo/?categoria=1 o /#seccion', max_length=200)),
                ('orden', models.PositiveIntegerField(default=0, help_text='Número para ordenar los slides. Menor número aparece primero.')),
                ('activo', models.BooleanField(default=True, help_text='Marcar para mostrar este slide en el carrusel.')),
            ],
            options={
                'verbose_name': 'Slide del Carrusel',
                'verbose_name_plural': 'Slides del Carrusel',
                'ordering': ['orden'],
            },
        ),
    ]
