# Generated by Django 4.2.25 on 2025-10-22 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_slide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Tamaño recomendado: 1200x600px', null=True, upload_to='slides/'),
        ),
    ]
