# Generated by Django 4.2.25 on 2025-10-29 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_pedido_nombre_referencia_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='en_promocion',
            field=models.BooleanField(default=False, verbose_name='En Promoción'),
        ),
    ]
